<!-- 
www.vnlisting.com
Online Super Bowl Squares Script
Please read the "Readme.txt for license agreement, installation and usage instructions 
-->

<!-- You may not and shall not make any changes to this file -->
<p>
<table width="95%" style="font-family: verdana, arial; font-size: 9px">
<tr>
<td>Copyright &copy; <?=date("Y")?> <a href="http://www.vnlisting.com/" title="VNLISTING" target="_parent">VNLISTING</a> modified by <a href="http://www.djsplice.com" title="DJSPLICE.COM" target="_parent">djsplice.com</a></td>
<td align="right">SB Squares v.<?=$VERSION?></td>
</tr>
</table>
</p>
</center>
<?php mysqli_close($conn);	?>
</body>
</html>
